### ISSUE TITLE
Firmware cannot be compiled when using a different esp32 eg(heltec esp32 wifi)

### ISSUE THREAD

**Issue by AikoKiss** [LucidVR/lucidgloves#69] opened 2022-04-14 15:36 UTC
Leaves error like Led not a type if not compiled with esp32dev

**Comment by JohnRThomas** [comment] 2022-04-14 19:50
Please open this issue on my fork as the problem is there :)

https://github.com/JohnRThomas/FlexiaGloves/issues

@danwillm I think you can close this

**Comment by danwillm** [comment] 2022-04-14 19:53
Cool, thanks, will do!

**Closed as completed by danwillm** 2022-04-14 19:53 UTC
